"""Deterministic core lifecycle proof with every external provider disabled."""
from datetime import datetime, timezone
from sqlalchemy import create_engine, select
from sqlalchemy.orm import sessionmaker
from app.core.database import Base
from app.core.audit import AuditLog
from app.domain.models import User, Applicant, Scheme, SchemeVersion, Application, Document
from app.domain.relational_models import (SchemeForm, SchemeDocument, SchemeWorkflow, ApplicationVersion, ApplicationStatusHistory, Institution, InstitutionVerificationRecord, Deficiency, DeficiencyResponse, ScrutinyReview, EligibilityRun, EligibilityResult, EligibilityRuleResult, SelectionRound, SelectionCandidate, SelectionScore, SelectionReview, Approval, Award, FinanceRecord, Notification, Grievance, GrievanceMessage)
from app.domain.selection_finance_models import CommitteeDecision
from app.domain.core_completion_models import FinanceInstallment, PaymentException

def test_complete_scholarship_lifecycle():
    engine=create_engine('sqlite:///:memory:'); Base.metadata.create_all(engine); db=sessionmaker(bind=engine)()
    admin=User(email='admin@demo',password_hash='hash',full_name='Admin',role='SUPER_ADMIN'); applicant_user=User(email='applicant@demo',password_hash='hash',full_name='Applicant',role='APPLICANT'); verifier=User(email='verifier@demo',password_hash='hash',full_name='Verifier',role='VERIFICATION_OFFICER'); committee=User(email='committee@demo',password_hash='hash',full_name='Committee',role='SELECTION_COMMITTEE_MEMBER'); approver=User(email='approver@demo',password_hash='hash',full_name='Approver',role='APPROVING_AUTHORITY'); finance=User(email='finance@demo',password_hash='hash',full_name='Finance',role='FINANCE_OFFICER'); db.add_all([admin,applicant_user,verifier,committee,approver,finance]); db.flush()
    applicant=Applicant(user_id=applicant_user.id,profile={'category':'DEMO'}); scheme=Scheme(code='DEMO-LIFECYCLE',name='DEMO_CONFIGURATION_NOT_OFFICIAL'); db.add_all([applicant,scheme]); db.flush()
    version=SchemeVersion(scheme_id=scheme.id,version='1',status='PUBLISHED',configuration={'source_reference':'DEMO_CONFIGURATION_NOT_OFFICIAL'}); db.add(version); db.flush()
    db.add_all([SchemeForm(scheme_version_id=version.id,definition={'fields':[{'key':'name','type':'text','required':True}]}),SchemeDocument(scheme_version_id=version.id,document_code='IDENTITY',label='Identity',required=True),SchemeWorkflow(scheme_version_id=version.id,definition={'transitions':[{'from':'DRAFT','to':'SUBMITTED'},{'from':'SUBMITTED','to':'SCRUTINY'},{'from':'SCRUTINY','to':'ELIGIBILITY_CONFIRMED'},{'from':'ELIGIBILITY_CONFIRMED','to':'SELECTION_REVIEW'},{'from':'SELECTION_REVIEW','to':'FINAL_APPROVAL'},{'from':'FINAL_APPROVAL','to':'AWARDED'}]})]); db.flush()
    application=Application(application_number='DEMO-000001',applicant_id=applicant.id,scheme_id=scheme.id,scheme_version_id=version.id,cycle='2026',answers={'name':'Applicant'},status='DRAFT'); db.add(application); db.flush(); db.add(ApplicationVersion(application_id=application.id,version_number=1,actor_id=applicant_user.id,snapshot=application.answers,reason='CREATED'))
    document=Document(application_id=application.id,uploaded_by=applicant_user.id,document_type='IDENTITY',filename='identity.pdf',mime='application/pdf',size=3,sha256='abc',storage_key='mock/identity',provider='mock',status='VERIFIED'); db.add(document); db.flush()
    application.status='SUBMITTED'; db.add(ApplicationStatusHistory(application_id=application.id,from_status='DRAFT',to_status='SUBMITTED',actor_id=applicant_user.id,reason='submit'))
    institution=Institution(code='INST-DEMO',name='Demo Institution'); db.add(institution); db.flush(); db.add(InstitutionVerificationRecord(application_id=application.id,institution_id=institution.id,verifier_id=verifier.id,result='VERIFIED',fields={'admission':True}))
    deficiency=Deficiency(application_id=application.id,raised_by=verifier.id,status='OPEN',type='CLARIFICATION',description='Demo clarification',severity='LOW',required_action='Respond'); db.add(deficiency); db.flush(); db.add(DeficiencyResponse(deficiency_id=deficiency.id,responded_by=applicant_user.id,response='Resolved')); deficiency.status='RESOLVED'
    scrutiny=ScrutinyReview(application_id=application.id,officer_id=verifier.id,status='COMPLETED',decision='COMPLETE',notes='Passed'); db.add(scrutiny)
    run=EligibilityRun(application_id=application.id,scheme_version_id=version.id,result='ELIGIBLE',engine_version='deterministic-1',input_snapshot=application.answers); db.add(run); db.flush(); db.add_all([EligibilityResult(run_id=run.id,result='ELIGIBLE',explanation={'deterministic':True}),EligibilityRuleResult(run_id=run.id,rule_id='DEMO',rule_name='Demo',operator='EQUALS',observed_value=True,expected_value=True,passed=True,source_reference='DEMO_CONFIGURATION_NOT_OFFICIAL')]); application.status='ELIGIBILITY_CONFIRMED'
    selection=SelectionRound(scheme_version_id=version.id,name='Demo Selection',status='OPEN'); db.add(selection); db.flush(); candidate=SelectionCandidate(round_id=selection.id,application_id=application.id,total_score=95); db.add(candidate); db.flush(); db.add_all([SelectionScore(candidate_id=candidate.id,criterion_code='MERIT',raw_value=95,normalized_value=95,weight=1,weighted_score=95),SelectionReview(candidate_id=candidate.id,member_id=committee.id,decision='RECOMMEND'),CommitteeDecision(candidate_id=candidate.id,member_id=committee.id,decision='APPROVE',rationale='Passed')]); candidate.rank=1; selection.status='FINALIZED'; selection.finalized_at=datetime.now(timezone.utc); selection.finalized_by=committee.id; application.status='FINAL_APPROVAL'
    approval=Approval(application_id=application.id,approver_id=approver.id,decision='APPROVED',note='Approved',packet_snapshot={'selection_finalized':True}); db.add(approval); award=Award(application_id=application.id,scheme_version_id=version.id,amount=1000,awarded_by=approver.id); db.add(award); db.flush(); installment=FinanceInstallment(award_id=award.id,installment_no=1,expected_amount=1000,status='PENDING'); db.add(installment); finance_record=FinanceRecord(award_id=award.id,record_type='DISBURSEMENT',amount=1000,status='RECORDED',provider='mock'); db.add(finance_record); db.flush(); db.add(PaymentException(finance_record_id=finance_record.id,expected_amount=1000,actual_amount=1000,difference=0,reason='Reconciled',status='RESOLVED',resolved_by=finance.id, resolved_at=datetime.now(timezone.utc))); db.add(Notification(user_id=applicant_user.id,channel='IN_APP',status='SENT',payload={'event':'AWARD'})); grievance=Grievance(applicant_id=applicant.id,created_by=applicant_user.id,category='Application',subject='Demo',description='Demo grievance',status='CLOSED'); db.add(grievance); db.flush(); db.add(GrievanceMessage(grievance_id=grievance.id,author_id=applicant_user.id,message='Closed')); application.status='AWARDED'; db.add(AuditLog(event_type='GOLDEN_LIFECYCLE_COMPLETED',actor_id=admin.id,entity_type='APPLICATION',entity_id=application.id,data={'ai':'off','providers':'mock'})); db.commit()
    assert db.scalar(select(Application).where(Application.id==application.id)).status=='AWARDED'
    assert db.scalar(select(Award).where(Award.application_id==application.id)) is not None
    assert db.scalar(select(FinanceRecord).where(FinanceRecord.award_id==award.id)) is not None
    assert db.scalar(select(AuditLog).where(AuditLog.event_type=='GOLDEN_LIFECYCLE_COMPLETED')) is not None
