from sqlalchemy import String,DateTime,JSON,Text,Boolean,Integer,ForeignKey,UniqueConstraint
from sqlalchemy.orm import Mapped,mapped_column
from app.core.database import Base
from datetime import datetime,timezone
import uuid
def uid(): return str(uuid.uuid4())
def now(): return datetime.now(timezone.utc)
class User(Base):
 __tablename__="users"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); email:Mapped[str]=mapped_column(String(320),unique=True,index=True); password_hash:Mapped[str]=mapped_column(String(255)); full_name:Mapped[str]=mapped_column(String(200)); role:Mapped[str]=mapped_column(String(80),default="APPLICANT",index=True); is_active:Mapped[bool]=mapped_column(Boolean,default=True); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class Applicant(Base):
 __tablename__="applicants"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); user_id:Mapped[str]=mapped_column(String(36),ForeignKey("users.id"),unique=True); profile:Mapped[dict]=mapped_column(JSON,default=dict)
class Scheme(Base):
 __tablename__="schemes"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); code:Mapped[str]=mapped_column(String(50),unique=True,index=True); name:Mapped[str]=mapped_column(String(255)); description:Mapped[str|None]=mapped_column(Text); active:Mapped[bool]=mapped_column(Boolean,default=True)
class SchemeVersion(Base):
 __tablename__="scheme_versions"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); scheme_id:Mapped[str]=mapped_column(String(36),ForeignKey("schemes.id"),index=True); version:Mapped[str]=mapped_column(String(30)); status:Mapped[str]=mapped_column(String(30),default="DRAFT",index=True); configuration:Mapped[dict]=mapped_column(JSON,default=dict); published_at:Mapped[datetime|None]=mapped_column(DateTime(timezone=True)); __table_args__=(UniqueConstraint("scheme_id","version"),)
class SchemeRule(Base):
 __tablename__="scheme_rules"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); scheme_version_id:Mapped[str]=mapped_column(String(36),ForeignKey("scheme_versions.id"),index=True); rule_id:Mapped[str]=mapped_column(String(80)); name:Mapped[str]=mapped_column(String(255)); field:Mapped[str]=mapped_column(String(255)); operator:Mapped[str]=mapped_column(String(50)); value:Mapped[object]=mapped_column(JSON); source_reference:Mapped[str]=mapped_column(String(500)); effective_from:Mapped[datetime|None]=mapped_column(DateTime(timezone=True))
class Application(Base):
 __tablename__="applications"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); application_number:Mapped[str]=mapped_column(String(40),unique=True,index=True); applicant_id:Mapped[str]=mapped_column(String(36),ForeignKey("applicants.id"),index=True); scheme_id:Mapped[str]=mapped_column(String(36),ForeignKey("schemes.id"),index=True); scheme_version_id:Mapped[str]=mapped_column(String(36),ForeignKey("scheme_versions.id")); cycle:Mapped[str]=mapped_column(String(20),index=True); status:Mapped[str]=mapped_column(String(40),default="DRAFT",index=True); answers:Mapped[dict]=mapped_column(JSON,default=dict); version:Mapped[int]=mapped_column(Integer,default=1); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now); __table_args__=(UniqueConstraint("applicant_id","scheme_id","cycle",name="uq_application_cycle"),)
class Document(Base):
 __tablename__="documents"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); application_id:Mapped[str|None]=mapped_column(String(36),ForeignKey("applications.id"),index=True); uploaded_by:Mapped[str]=mapped_column(String(36),ForeignKey("users.id")); filename:Mapped[str]=mapped_column(String(255)); document_type:Mapped[str|None]=mapped_column(String(100),nullable=True); mime:Mapped[str]=mapped_column(String(100)); size:Mapped[int]=mapped_column(Integer); sha256:Mapped[str]=mapped_column(String(64)); storage_key:Mapped[str]=mapped_column(String(500)); provider:Mapped[str]=mapped_column(String(40),default="cloudinary"); status:Mapped[str]=mapped_column(String(30),default="PENDING"); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now)
class GenericRecord(Base):
 __tablename__="module_records"; id:Mapped[str]=mapped_column(String(36),primary_key=True,default=uid); module:Mapped[str]=mapped_column(String(80),index=True); record_type:Mapped[str]=mapped_column(String(80),index=True); owner_id:Mapped[str|None]=mapped_column(String(36),index=True); status:Mapped[str|None]=mapped_column(String(40),index=True); data:Mapped[dict]=mapped_column(JSON,default=dict); created_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now); updated_at:Mapped[datetime]=mapped_column(DateTime(timezone=True),default=now,onupdate=now)
