/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ApprovalRouteImport } from './routes/approval'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as CommitteeRouteImport } from './routes/committee'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqsRouteImport } from './routes/faqs'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ForbiddenRouteImport } from './routes/forbidden'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as GrievanceRouteImport } from './routes/grievance'
import { Route as GuidelinesRouteImport } from './routes/guidelines'
import { Route as InstitutionRouteImport } from './routes/institution'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as OfficerRouteImport } from './routes/officer'
import { Route as OtpVerifyRouteImport } from './routes/otp-verify'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAiRouteImport } from './routes/admin/ai'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminNotificationTemplatesRouteImport } from './routes/admin/notification-templates'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminPermissionsRouteImport } from './routes/admin/permissions'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSchemesRouteImport } from './routes/admin/schemes'
import { Route as AdminScopesRouteImport } from './routes/admin/scopes'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AnalyticsIndexRouteImport } from './routes/analytics/index'
import { Route as AnalyticsAiRouteImport } from './routes/analytics/ai'
import { Route as AnalyticsOperationalRouteImport } from './routes/analytics/operational'
import { Route as AnalyticsProcessingRouteImport } from './routes/analytics/processing'
import { Route as AnalyticsSchemeRouteImport } from './routes/analytics/scheme'
import { Route as AnalyticsSelectionRouteImport } from './routes/analytics/selection'
import { Route as ApprovalIndexRouteImport } from './routes/approval/index'
import { Route as ApprovalQueueRouteImport } from './routes/approval/queue'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AuditLogRouteImport } from './routes/audit/log'
import { Route as CommitteeIndexRouteImport } from './routes/committee/index'
import { Route as CommitteeCandidatesRouteImport } from './routes/committee/candidates'
import { Route as FinanceIndexRouteImport } from './routes/finance/index'
import { Route as FinanceAwardsRouteImport } from './routes/finance/awards'
import { Route as FinanceDisbursementsRouteImport } from './routes/finance/disbursements'
import { Route as FinanceExceptionsRouteImport } from './routes/finance/exceptions'
import { Route as FinanceReconciliationRouteImport } from './routes/finance/reconciliation'
import { Route as FinanceSanctionsRouteImport } from './routes/finance/sanctions'
import { Route as InstitutionIndexRouteImport } from './routes/institution/index'
import { Route as InstitutionClarificationsRouteImport } from './routes/institution/clarifications'
import { Route as InstitutionUsersRouteImport } from './routes/institution/users'
import { Route as InstitutionVerificationsRouteImport } from './routes/institution/verifications'
import { Route as OfficerIndexRouteImport } from './routes/officer/index'
import { Route as OfficerClarificationsRouteImport } from './routes/officer/clarifications'
import { Route as OfficerDeficienciesRouteImport } from './routes/officer/deficiencies'
import { Route as OfficerNotificationsRouteImport } from './routes/officer/notifications'
import { Route as OfficerQueueRouteImport } from './routes/officer/queue'
import { Route as PortalIndexRouteImport } from './routes/portal/index'
import { Route as PortalAwardsRouteImport } from './routes/portal/awards'
import { Route as PortalDeficienciesRouteImport } from './routes/portal/deficiencies'
import { Route as PortalDocumentsRouteImport } from './routes/portal/documents'
import { Route as PortalNotificationsRouteImport } from './routes/portal/notifications'
import { Route as PortalProfileRouteImport } from './routes/portal/profile'
import { Route as SchemesIndexRouteImport } from './routes/schemes.index'
import { Route as SchemesIdRouteImport } from './routes/schemes.$id'
import { Route as AdminSchemesIdRouteImport } from './routes/admin/schemes.$id'
import { Route as ApprovalApplicationsIdRouteImport } from './routes/approval/applications.$id'
import { Route as AuditEventsIdRouteImport } from './routes/audit/events.$id'
import { Route as CommitteeCandidatesIdRouteImport } from './routes/committee/candidates.$id'
import { Route as InstitutionApplicationsIndexRouteImport } from './routes/institution/applications.index'
import { Route as InstitutionApplicationsIdRouteImport } from './routes/institution/applications.$id'
import { Route as OfficerApplicationsIdRouteImport } from './routes/officer/applications.$id'
import { Route as OfficerGrievancesIndexRouteImport } from './routes/officer/grievances.index'
import { Route as OfficerGrievancesIdRouteImport } from './routes/officer/grievances.$id'
import { Route as PortalApplicationsIndexRouteImport } from './routes/portal/applications.index'
import { Route as PortalApplicationsIdRouteImport } from './routes/portal/applications.$id'
import { Route as PortalApplicationsNewRouteImport } from './routes/portal/applications.new'
import { Route as PortalGrievancesIndexRouteImport } from './routes/portal/grievances.index'
import { Route as PortalGrievancesIdRouteImport } from './routes/portal/grievances.$id'
import { Route as PortalGrievancesNewRouteImport } from './routes/portal/grievances.new'
import { Route as PortalApplicationsIdDeficiencyRouteImport } from './routes/portal/applications.$id.deficiency'
import { Route as PortalApplicationsIdDocumentsRouteImport } from './routes/portal/applications.$id.documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalRoute = ApprovalRouteImport.update({
  id: '/approval',
  path: '/approval',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const CommitteeRoute = CommitteeRouteImport.update({
  id: '/committee',
  path: '/committee',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqsRoute = FaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForbiddenRoute = ForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const GrievanceRoute = GrievanceRouteImport.update({
  id: '/grievance',
  path: '/grievance',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesRoute = GuidelinesRouteImport.update({
  id: '/guidelines',
  path: '/guidelines',
  getParentRoute: () => rootRouteImport,
} as any)
const InstitutionRoute = InstitutionRouteImport.update({
  id: '/institution',
  path: '/institution',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficerRoute = OfficerRouteImport.update({
  id: '/officer',
  path: '/officer',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpVerifyRoute = OtpVerifyRouteImport.update({
  id: '/otp-verify',
  path: '/otp-verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiRoute = AdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationTemplatesRoute =
  AdminNotificationTemplatesRouteImport.update({
    id: '/notification-templates',
    path: '/notification-templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPermissionsRoute = AdminPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchemesRoute = AdminSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScopesRoute = AdminScopesRouteImport.update({
  id: '/scopes',
  path: '/scopes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AnalyticsIndexRoute = AnalyticsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsAiRoute = AnalyticsAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsOperationalRoute = AnalyticsOperationalRouteImport.update({
  id: '/operational',
  path: '/operational',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsProcessingRoute = AnalyticsProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsSchemeRoute = AnalyticsSchemeRouteImport.update({
  id: '/scheme',
  path: '/scheme',
  getParentRoute: () => AnalyticsRoute,
} as any)
const AnalyticsSelectionRoute = AnalyticsSelectionRouteImport.update({
  id: '/selection',
  path: '/selection',
  getParentRoute: () => AnalyticsRoute,
} as any)
const ApprovalIndexRoute = ApprovalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ApprovalRoute,
} as any)
const ApprovalQueueRoute = ApprovalQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => ApprovalRoute,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuditRoute,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => AuditRoute,
} as any)
const CommitteeIndexRoute = CommitteeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommitteeRoute,
} as any)
const CommitteeCandidatesRoute = CommitteeCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => CommitteeRoute,
} as any)
const FinanceIndexRoute = FinanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceAwardsRoute = FinanceAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceDisbursementsRoute = FinanceDisbursementsRouteImport.update({
  id: '/disbursements',
  path: '/disbursements',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceExceptionsRoute = FinanceExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceReconciliationRoute = FinanceReconciliationRouteImport.update({
  id: '/reconciliation',
  path: '/reconciliation',
  getParentRoute: () => FinanceRoute,
} as any)
const FinanceSanctionsRoute = FinanceSanctionsRouteImport.update({
  id: '/sanctions',
  path: '/sanctions',
  getParentRoute: () => FinanceRoute,
} as any)
const InstitutionIndexRoute = InstitutionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionClarificationsRoute =
  InstitutionClarificationsRouteImport.update({
    id: '/clarifications',
    path: '/clarifications',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionUsersRoute = InstitutionUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => InstitutionRoute,
} as any)
const InstitutionVerificationsRoute =
  InstitutionVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => InstitutionRoute,
  } as any)
const OfficerIndexRoute = OfficerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerClarificationsRoute = OfficerClarificationsRouteImport.update({
  id: '/clarifications',
  path: '/clarifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerDeficienciesRoute = OfficerDeficienciesRouteImport.update({
  id: '/deficiencies',
  path: '/deficiencies',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerNotificationsRoute = OfficerNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerQueueRoute = OfficerQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => OfficerRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAwardsRoute = PortalAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDeficienciesRoute = PortalDeficienciesRouteImport.update({
  id: '/deficiencies',
  path: '/deficiencies',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalNotificationsRoute = PortalNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const SchemesIndexRoute = SchemesIndexRouteImport.update({
  id: '/schemes/',
  path: '/schemes/',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesIdRoute = SchemesIdRouteImport.update({
  id: '/schemes/$id',
  path: '/schemes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSchemesIdRoute = AdminSchemesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSchemesRoute,
} as any)
const ApprovalApplicationsIdRoute = ApprovalApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => ApprovalRoute,
} as any)
const AuditEventsIdRoute = AuditEventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuditRoute,
} as any)
const CommitteeCandidatesIdRoute = CommitteeCandidatesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommitteeCandidatesRoute,
} as any)
const InstitutionApplicationsIndexRoute =
  InstitutionApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => InstitutionRoute,
  } as any)
const InstitutionApplicationsIdRoute =
  InstitutionApplicationsIdRouteImport.update({
    id: '/applications/$id',
    path: '/applications/$id',
    getParentRoute: () => InstitutionRoute,
  } as any)
const OfficerApplicationsIdRoute = OfficerApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerGrievancesIndexRoute = OfficerGrievancesIndexRouteImport.update({
  id: '/grievances/',
  path: '/grievances/',
  getParentRoute: () => OfficerRoute,
} as any)
const OfficerGrievancesIdRoute = OfficerGrievancesIdRouteImport.update({
  id: '/grievances/$id',
  path: '/grievances/$id',
  getParentRoute: () => OfficerRoute,
} as any)
const PortalApplicationsIndexRoute = PortalApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationsIdRoute = PortalApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationsNewRoute = PortalApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGrievancesIndexRoute = PortalGrievancesIndexRouteImport.update({
  id: '/grievances/',
  path: '/grievances/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGrievancesIdRoute = PortalGrievancesIdRouteImport.update({
  id: '/grievances/$id',
  path: '/grievances/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalGrievancesNewRoute = PortalGrievancesNewRouteImport.update({
  id: '/grievances/new',
  path: '/grievances/new',
  getParentRoute: () => PortalRoute,
} as any)
const PortalApplicationsIdDeficiencyRoute =
  PortalApplicationsIdDeficiencyRouteImport.update({
    id: '/deficiency',
    path: '/deficiency',
    getParentRoute: () => PortalApplicationsIdRoute,
  } as any)
const PortalApplicationsIdDocumentsRoute =
  PortalApplicationsIdDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => PortalApplicationsIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/approval': typeof ApprovalRouteWithChildren
  '/audit': typeof AuditRouteWithChildren
  '/committee': typeof CommitteeRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/notices': typeof NoticesRoute
  '/officer': typeof OfficerRouteWithChildren
  '/otp-verify': typeof OtpVerifyRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/notification-templates': typeof AdminNotificationTemplatesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schemes': typeof AdminSchemesRouteWithChildren
  '/admin/scopes': typeof AdminScopesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ai': typeof AnalyticsAiRoute
  '/analytics/operational': typeof AnalyticsOperationalRoute
  '/analytics/processing': typeof AnalyticsProcessingRoute
  '/analytics/scheme': typeof AnalyticsSchemeRoute
  '/analytics/selection': typeof AnalyticsSelectionRoute
  '/approval/queue': typeof ApprovalQueueRoute
  '/audit/log': typeof AuditLogRoute
  '/committee/candidates': typeof CommitteeCandidatesRouteWithChildren
  '/finance/awards': typeof FinanceAwardsRoute
  '/finance/disbursements': typeof FinanceDisbursementsRoute
  '/finance/exceptions': typeof FinanceExceptionsRoute
  '/finance/reconciliation': typeof FinanceReconciliationRoute
  '/finance/sanctions': typeof FinanceSanctionsRoute
  '/institution/clarifications': typeof InstitutionClarificationsRoute
  '/institution/users': typeof InstitutionUsersRoute
  '/institution/verifications': typeof InstitutionVerificationsRoute
  '/officer/clarifications': typeof OfficerClarificationsRoute
  '/officer/deficiencies': typeof OfficerDeficienciesRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/portal/awards': typeof PortalAwardsRoute
  '/portal/deficiencies': typeof PortalDeficienciesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/approval/': typeof ApprovalIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/committee/': typeof CommitteeIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/admin/schemes/$id': typeof AdminSchemesIdRoute
  '/approval/applications/$id': typeof ApprovalApplicationsIdRoute
  '/audit/events/$id': typeof AuditEventsIdRoute
  '/committee/candidates/$id': typeof CommitteeCandidatesIdRoute
  '/institution/applications/$id': typeof InstitutionApplicationsIdRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/officer/grievances/$id': typeof OfficerGrievancesIdRoute
  '/portal/applications/$id': typeof PortalApplicationsIdRouteWithChildren
  '/portal/applications/new': typeof PortalApplicationsNewRoute
  '/portal/grievances/$id': typeof PortalGrievancesIdRoute
  '/portal/grievances/new': typeof PortalGrievancesNewRoute
  '/institution/applications/': typeof InstitutionApplicationsIndexRoute
  '/officer/grievances/': typeof OfficerGrievancesIndexRoute
  '/portal/applications/': typeof PortalApplicationsIndexRoute
  '/portal/grievances/': typeof PortalGrievancesIndexRoute
  '/portal/applications/$id/deficiency': typeof PortalApplicationsIdDeficiencyRoute
  '/portal/applications/$id/documents': typeof PortalApplicationsIdDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/notices': typeof NoticesRoute
  '/otp-verify': typeof OtpVerifyRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/notification-templates': typeof AdminNotificationTemplatesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schemes': typeof AdminSchemesRouteWithChildren
  '/admin/scopes': typeof AdminScopesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ai': typeof AnalyticsAiRoute
  '/analytics/operational': typeof AnalyticsOperationalRoute
  '/analytics/processing': typeof AnalyticsProcessingRoute
  '/analytics/scheme': typeof AnalyticsSchemeRoute
  '/analytics/selection': typeof AnalyticsSelectionRoute
  '/approval/queue': typeof ApprovalQueueRoute
  '/audit/log': typeof AuditLogRoute
  '/committee/candidates': typeof CommitteeCandidatesRouteWithChildren
  '/finance/awards': typeof FinanceAwardsRoute
  '/finance/disbursements': typeof FinanceDisbursementsRoute
  '/finance/exceptions': typeof FinanceExceptionsRoute
  '/finance/reconciliation': typeof FinanceReconciliationRoute
  '/finance/sanctions': typeof FinanceSanctionsRoute
  '/institution/clarifications': typeof InstitutionClarificationsRoute
  '/institution/users': typeof InstitutionUsersRoute
  '/institution/verifications': typeof InstitutionVerificationsRoute
  '/officer/clarifications': typeof OfficerClarificationsRoute
  '/officer/deficiencies': typeof OfficerDeficienciesRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/portal/awards': typeof PortalAwardsRoute
  '/portal/deficiencies': typeof PortalDeficienciesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/admin': typeof AdminIndexRoute
  '/analytics': typeof AnalyticsIndexRoute
  '/approval': typeof ApprovalIndexRoute
  '/audit': typeof AuditIndexRoute
  '/committee': typeof CommitteeIndexRoute
  '/finance': typeof FinanceIndexRoute
  '/institution': typeof InstitutionIndexRoute
  '/officer': typeof OfficerIndexRoute
  '/portal': typeof PortalIndexRoute
  '/schemes': typeof SchemesIndexRoute
  '/admin/schemes/$id': typeof AdminSchemesIdRoute
  '/approval/applications/$id': typeof ApprovalApplicationsIdRoute
  '/audit/events/$id': typeof AuditEventsIdRoute
  '/committee/candidates/$id': typeof CommitteeCandidatesIdRoute
  '/institution/applications/$id': typeof InstitutionApplicationsIdRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/officer/grievances/$id': typeof OfficerGrievancesIdRoute
  '/portal/applications/$id': typeof PortalApplicationsIdRouteWithChildren
  '/portal/applications/new': typeof PortalApplicationsNewRoute
  '/portal/grievances/$id': typeof PortalGrievancesIdRoute
  '/portal/grievances/new': typeof PortalGrievancesNewRoute
  '/institution/applications': typeof InstitutionApplicationsIndexRoute
  '/officer/grievances': typeof OfficerGrievancesIndexRoute
  '/portal/applications': typeof PortalApplicationsIndexRoute
  '/portal/grievances': typeof PortalGrievancesIndexRoute
  '/portal/applications/$id/deficiency': typeof PortalApplicationsIdDeficiencyRoute
  '/portal/applications/$id/documents': typeof PortalApplicationsIdDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRouteWithChildren
  '/approval': typeof ApprovalRouteWithChildren
  '/audit': typeof AuditRouteWithChildren
  '/committee': typeof CommitteeRouteWithChildren
  '/contact': typeof ContactRoute
  '/faqs': typeof FaqsRoute
  '/finance': typeof FinanceRouteWithChildren
  '/forbidden': typeof ForbiddenRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/grievance': typeof GrievanceRoute
  '/guidelines': typeof GuidelinesRoute
  '/institution': typeof InstitutionRouteWithChildren
  '/login': typeof LoginRoute
  '/mfa': typeof MfaRoute
  '/notices': typeof NoticesRoute
  '/officer': typeof OfficerRouteWithChildren
  '/otp-verify': typeof OtpVerifyRoute
  '/portal': typeof PortalRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/admin/ai': typeof AdminAiRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/notification-templates': typeof AdminNotificationTemplatesRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/permissions': typeof AdminPermissionsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schemes': typeof AdminSchemesRouteWithChildren
  '/admin/scopes': typeof AdminScopesRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/analytics/ai': typeof AnalyticsAiRoute
  '/analytics/operational': typeof AnalyticsOperationalRoute
  '/analytics/processing': typeof AnalyticsProcessingRoute
  '/analytics/scheme': typeof AnalyticsSchemeRoute
  '/analytics/selection': typeof AnalyticsSelectionRoute
  '/approval/queue': typeof ApprovalQueueRoute
  '/audit/log': typeof AuditLogRoute
  '/committee/candidates': typeof CommitteeCandidatesRouteWithChildren
  '/finance/awards': typeof FinanceAwardsRoute
  '/finance/disbursements': typeof FinanceDisbursementsRoute
  '/finance/exceptions': typeof FinanceExceptionsRoute
  '/finance/reconciliation': typeof FinanceReconciliationRoute
  '/finance/sanctions': typeof FinanceSanctionsRoute
  '/institution/clarifications': typeof InstitutionClarificationsRoute
  '/institution/users': typeof InstitutionUsersRoute
  '/institution/verifications': typeof InstitutionVerificationsRoute
  '/officer/clarifications': typeof OfficerClarificationsRoute
  '/officer/deficiencies': typeof OfficerDeficienciesRoute
  '/officer/notifications': typeof OfficerNotificationsRoute
  '/officer/queue': typeof OfficerQueueRoute
  '/portal/awards': typeof PortalAwardsRoute
  '/portal/deficiencies': typeof PortalDeficienciesRoute
  '/portal/documents': typeof PortalDocumentsRoute
  '/portal/notifications': typeof PortalNotificationsRoute
  '/portal/profile': typeof PortalProfileRoute
  '/schemes/$id': typeof SchemesIdRoute
  '/admin/': typeof AdminIndexRoute
  '/analytics/': typeof AnalyticsIndexRoute
  '/approval/': typeof ApprovalIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/committee/': typeof CommitteeIndexRoute
  '/finance/': typeof FinanceIndexRoute
  '/institution/': typeof InstitutionIndexRoute
  '/officer/': typeof OfficerIndexRoute
  '/portal/': typeof PortalIndexRoute
  '/schemes/': typeof SchemesIndexRoute
  '/admin/schemes/$id': typeof AdminSchemesIdRoute
  '/approval/applications/$id': typeof ApprovalApplicationsIdRoute
  '/audit/events/$id': typeof AuditEventsIdRoute
  '/committee/candidates/$id': typeof CommitteeCandidatesIdRoute
  '/institution/applications/$id': typeof InstitutionApplicationsIdRoute
  '/officer/applications/$id': typeof OfficerApplicationsIdRoute
  '/officer/grievances/$id': typeof OfficerGrievancesIdRoute
  '/portal/applications/$id': typeof PortalApplicationsIdRouteWithChildren
  '/portal/applications/new': typeof PortalApplicationsNewRoute
  '/portal/grievances/$id': typeof PortalGrievancesIdRoute
  '/portal/grievances/new': typeof PortalGrievancesNewRoute
  '/institution/applications/': typeof InstitutionApplicationsIndexRoute
  '/officer/grievances/': typeof OfficerGrievancesIndexRoute
  '/portal/applications/': typeof PortalApplicationsIndexRoute
  '/portal/grievances/': typeof PortalGrievancesIndexRoute
  '/portal/applications/$id/deficiency': typeof PortalApplicationsIdDeficiencyRoute
  '/portal/applications/$id/documents': typeof PortalApplicationsIdDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/audit'
    | '/committee'
    | '/contact'
    | '/faqs'
    | '/finance'
    | '/forbidden'
    | '/forgot-password'
    | '/grievance'
    | '/guidelines'
    | '/institution'
    | '/login'
    | '/mfa'
    | '/notices'
    | '/officer'
    | '/otp-verify'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/admin/ai'
    | '/admin/integrations'
    | '/admin/notification-templates'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/schemes'
    | '/admin/scopes'
    | '/admin/system'
    | '/admin/users'
    | '/analytics/ai'
    | '/analytics/operational'
    | '/analytics/processing'
    | '/analytics/scheme'
    | '/analytics/selection'
    | '/approval/queue'
    | '/audit/log'
    | '/committee/candidates'
    | '/finance/awards'
    | '/finance/disbursements'
    | '/finance/exceptions'
    | '/finance/reconciliation'
    | '/finance/sanctions'
    | '/institution/clarifications'
    | '/institution/users'
    | '/institution/verifications'
    | '/officer/clarifications'
    | '/officer/deficiencies'
    | '/officer/notifications'
    | '/officer/queue'
    | '/portal/awards'
    | '/portal/deficiencies'
    | '/portal/documents'
    | '/portal/notifications'
    | '/portal/profile'
    | '/schemes/$id'
    | '/admin/'
    | '/analytics/'
    | '/approval/'
    | '/audit/'
    | '/committee/'
    | '/finance/'
    | '/institution/'
    | '/officer/'
    | '/portal/'
    | '/schemes/'
    | '/admin/schemes/$id'
    | '/approval/applications/$id'
    | '/audit/events/$id'
    | '/committee/candidates/$id'
    | '/institution/applications/$id'
    | '/officer/applications/$id'
    | '/officer/grievances/$id'
    | '/portal/applications/$id'
    | '/portal/applications/new'
    | '/portal/grievances/$id'
    | '/portal/grievances/new'
    | '/institution/applications/'
    | '/officer/grievances/'
    | '/portal/applications/'
    | '/portal/grievances/'
    | '/portal/applications/$id/deficiency'
    | '/portal/applications/$id/documents'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faqs'
    | '/forbidden'
    | '/forgot-password'
    | '/grievance'
    | '/guidelines'
    | '/login'
    | '/mfa'
    | '/notices'
    | '/otp-verify'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/admin/ai'
    | '/admin/integrations'
    | '/admin/notification-templates'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/schemes'
    | '/admin/scopes'
    | '/admin/system'
    | '/admin/users'
    | '/analytics/ai'
    | '/analytics/operational'
    | '/analytics/processing'
    | '/analytics/scheme'
    | '/analytics/selection'
    | '/approval/queue'
    | '/audit/log'
    | '/committee/candidates'
    | '/finance/awards'
    | '/finance/disbursements'
    | '/finance/exceptions'
    | '/finance/reconciliation'
    | '/finance/sanctions'
    | '/institution/clarifications'
    | '/institution/users'
    | '/institution/verifications'
    | '/officer/clarifications'
    | '/officer/deficiencies'
    | '/officer/notifications'
    | '/officer/queue'
    | '/portal/awards'
    | '/portal/deficiencies'
    | '/portal/documents'
    | '/portal/notifications'
    | '/portal/profile'
    | '/schemes/$id'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/audit'
    | '/committee'
    | '/finance'
    | '/institution'
    | '/officer'
    | '/portal'
    | '/schemes'
    | '/admin/schemes/$id'
    | '/approval/applications/$id'
    | '/audit/events/$id'
    | '/committee/candidates/$id'
    | '/institution/applications/$id'
    | '/officer/applications/$id'
    | '/officer/grievances/$id'
    | '/portal/applications/$id'
    | '/portal/applications/new'
    | '/portal/grievances/$id'
    | '/portal/grievances/new'
    | '/institution/applications'
    | '/officer/grievances'
    | '/portal/applications'
    | '/portal/grievances'
    | '/portal/applications/$id/deficiency'
    | '/portal/applications/$id/documents'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/approval'
    | '/audit'
    | '/committee'
    | '/contact'
    | '/faqs'
    | '/finance'
    | '/forbidden'
    | '/forgot-password'
    | '/grievance'
    | '/guidelines'
    | '/institution'
    | '/login'
    | '/mfa'
    | '/notices'
    | '/officer'
    | '/otp-verify'
    | '/portal'
    | '/register'
    | '/reset-password'
    | '/session-expired'
    | '/admin/ai'
    | '/admin/integrations'
    | '/admin/notification-templates'
    | '/admin/notifications'
    | '/admin/permissions'
    | '/admin/roles'
    | '/admin/schemes'
    | '/admin/scopes'
    | '/admin/system'
    | '/admin/users'
    | '/analytics/ai'
    | '/analytics/operational'
    | '/analytics/processing'
    | '/analytics/scheme'
    | '/analytics/selection'
    | '/approval/queue'
    | '/audit/log'
    | '/committee/candidates'
    | '/finance/awards'
    | '/finance/disbursements'
    | '/finance/exceptions'
    | '/finance/reconciliation'
    | '/finance/sanctions'
    | '/institution/clarifications'
    | '/institution/users'
    | '/institution/verifications'
    | '/officer/clarifications'
    | '/officer/deficiencies'
    | '/officer/notifications'
    | '/officer/queue'
    | '/portal/awards'
    | '/portal/deficiencies'
    | '/portal/documents'
    | '/portal/notifications'
    | '/portal/profile'
    | '/schemes/$id'
    | '/admin/'
    | '/analytics/'
    | '/approval/'
    | '/audit/'
    | '/committee/'
    | '/finance/'
    | '/institution/'
    | '/officer/'
    | '/portal/'
    | '/schemes/'
    | '/admin/schemes/$id'
    | '/approval/applications/$id'
    | '/audit/events/$id'
    | '/committee/candidates/$id'
    | '/institution/applications/$id'
    | '/officer/applications/$id'
    | '/officer/grievances/$id'
    | '/portal/applications/$id'
    | '/portal/applications/new'
    | '/portal/grievances/$id'
    | '/portal/grievances/new'
    | '/institution/applications/'
    | '/officer/grievances/'
    | '/portal/applications/'
    | '/portal/grievances/'
    | '/portal/applications/$id/deficiency'
    | '/portal/applications/$id/documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRouteWithChildren
  ApprovalRoute: typeof ApprovalRouteWithChildren
  AuditRoute: typeof AuditRouteWithChildren
  CommitteeRoute: typeof CommitteeRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqsRoute: typeof FaqsRoute
  FinanceRoute: typeof FinanceRouteWithChildren
  ForbiddenRoute: typeof ForbiddenRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GrievanceRoute: typeof GrievanceRoute
  GuidelinesRoute: typeof GuidelinesRoute
  InstitutionRoute: typeof InstitutionRouteWithChildren
  LoginRoute: typeof LoginRoute
  MfaRoute: typeof MfaRoute
  NoticesRoute: typeof NoticesRoute
  OfficerRoute: typeof OfficerRouteWithChildren
  OtpVerifyRoute: typeof OtpVerifyRoute
  PortalRoute: typeof PortalRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SchemesIdRoute: typeof SchemesIdRoute
  SchemesIndexRoute: typeof SchemesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approval': {
      id: '/approval'
      path: '/approval'
      fullPath: '/approval'
      preLoaderRoute: typeof ApprovalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/committee': {
      id: '/committee'
      path: '/committee'
      fullPath: '/committee'
      preLoaderRoute: typeof CommitteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faqs': {
      id: '/faqs'
      path: '/faqs'
      fullPath: '/faqs'
      preLoaderRoute: typeof FaqsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forbidden': {
      id: '/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof ForbiddenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grievance': {
      id: '/grievance'
      path: '/grievance'
      fullPath: '/grievance'
      preLoaderRoute: typeof GrievanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines': {
      id: '/guidelines'
      path: '/guidelines'
      fullPath: '/guidelines'
      preLoaderRoute: typeof GuidelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/institution': {
      id: '/institution'
      path: '/institution'
      fullPath: '/institution'
      preLoaderRoute: typeof InstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officer': {
      id: '/officer'
      path: '/officer'
      fullPath: '/officer'
      preLoaderRoute: typeof OfficerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp-verify': {
      id: '/otp-verify'
      path: '/otp-verify'
      fullPath: '/otp-verify'
      preLoaderRoute: typeof OtpVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai': {
      id: '/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AdminAiRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification-templates': {
      id: '/admin/notification-templates'
      path: '/notification-templates'
      fullPath: '/admin/notification-templates'
      preLoaderRoute: typeof AdminNotificationTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/permissions': {
      id: '/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AdminPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schemes': {
      id: '/admin/schemes'
      path: '/schemes'
      fullPath: '/admin/schemes'
      preLoaderRoute: typeof AdminSchemesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/scopes': {
      id: '/admin/scopes'
      path: '/scopes'
      fullPath: '/admin/scopes'
      preLoaderRoute: typeof AdminScopesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/analytics/': {
      id: '/analytics/'
      path: '/'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AnalyticsIndexRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/ai': {
      id: '/analytics/ai'
      path: '/ai'
      fullPath: '/analytics/ai'
      preLoaderRoute: typeof AnalyticsAiRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/operational': {
      id: '/analytics/operational'
      path: '/operational'
      fullPath: '/analytics/operational'
      preLoaderRoute: typeof AnalyticsOperationalRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/processing': {
      id: '/analytics/processing'
      path: '/processing'
      fullPath: '/analytics/processing'
      preLoaderRoute: typeof AnalyticsProcessingRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/scheme': {
      id: '/analytics/scheme'
      path: '/scheme'
      fullPath: '/analytics/scheme'
      preLoaderRoute: typeof AnalyticsSchemeRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/analytics/selection': {
      id: '/analytics/selection'
      path: '/selection'
      fullPath: '/analytics/selection'
      preLoaderRoute: typeof AnalyticsSelectionRouteImport
      parentRoute: typeof AnalyticsRoute
    }
    '/approval/': {
      id: '/approval/'
      path: '/'
      fullPath: '/approval/'
      preLoaderRoute: typeof ApprovalIndexRouteImport
      parentRoute: typeof ApprovalRoute
    }
    '/approval/queue': {
      id: '/approval/queue'
      path: '/queue'
      fullPath: '/approval/queue'
      preLoaderRoute: typeof ApprovalQueueRouteImport
      parentRoute: typeof ApprovalRoute
    }
    '/audit/': {
      id: '/audit/'
      path: '/'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof AuditRoute
    }
    '/audit/log': {
      id: '/audit/log'
      path: '/log'
      fullPath: '/audit/log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof AuditRoute
    }
    '/committee/': {
      id: '/committee/'
      path: '/'
      fullPath: '/committee/'
      preLoaderRoute: typeof CommitteeIndexRouteImport
      parentRoute: typeof CommitteeRoute
    }
    '/committee/candidates': {
      id: '/committee/candidates'
      path: '/candidates'
      fullPath: '/committee/candidates'
      preLoaderRoute: typeof CommitteeCandidatesRouteImport
      parentRoute: typeof CommitteeRoute
    }
    '/finance/': {
      id: '/finance/'
      path: '/'
      fullPath: '/finance/'
      preLoaderRoute: typeof FinanceIndexRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/awards': {
      id: '/finance/awards'
      path: '/awards'
      fullPath: '/finance/awards'
      preLoaderRoute: typeof FinanceAwardsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/disbursements': {
      id: '/finance/disbursements'
      path: '/disbursements'
      fullPath: '/finance/disbursements'
      preLoaderRoute: typeof FinanceDisbursementsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/exceptions': {
      id: '/finance/exceptions'
      path: '/exceptions'
      fullPath: '/finance/exceptions'
      preLoaderRoute: typeof FinanceExceptionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/reconciliation': {
      id: '/finance/reconciliation'
      path: '/reconciliation'
      fullPath: '/finance/reconciliation'
      preLoaderRoute: typeof FinanceReconciliationRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/finance/sanctions': {
      id: '/finance/sanctions'
      path: '/sanctions'
      fullPath: '/finance/sanctions'
      preLoaderRoute: typeof FinanceSanctionsRouteImport
      parentRoute: typeof FinanceRoute
    }
    '/institution/': {
      id: '/institution/'
      path: '/'
      fullPath: '/institution/'
      preLoaderRoute: typeof InstitutionIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/clarifications': {
      id: '/institution/clarifications'
      path: '/clarifications'
      fullPath: '/institution/clarifications'
      preLoaderRoute: typeof InstitutionClarificationsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/users': {
      id: '/institution/users'
      path: '/users'
      fullPath: '/institution/users'
      preLoaderRoute: typeof InstitutionUsersRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/verifications': {
      id: '/institution/verifications'
      path: '/verifications'
      fullPath: '/institution/verifications'
      preLoaderRoute: typeof InstitutionVerificationsRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/officer/': {
      id: '/officer/'
      path: '/'
      fullPath: '/officer/'
      preLoaderRoute: typeof OfficerIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/clarifications': {
      id: '/officer/clarifications'
      path: '/clarifications'
      fullPath: '/officer/clarifications'
      preLoaderRoute: typeof OfficerClarificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/deficiencies': {
      id: '/officer/deficiencies'
      path: '/deficiencies'
      fullPath: '/officer/deficiencies'
      preLoaderRoute: typeof OfficerDeficienciesRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/notifications': {
      id: '/officer/notifications'
      path: '/notifications'
      fullPath: '/officer/notifications'
      preLoaderRoute: typeof OfficerNotificationsRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/queue': {
      id: '/officer/queue'
      path: '/queue'
      fullPath: '/officer/queue'
      preLoaderRoute: typeof OfficerQueueRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/awards': {
      id: '/portal/awards'
      path: '/awards'
      fullPath: '/portal/awards'
      preLoaderRoute: typeof PortalAwardsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/deficiencies': {
      id: '/portal/deficiencies'
      path: '/deficiencies'
      fullPath: '/portal/deficiencies'
      preLoaderRoute: typeof PortalDeficienciesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/documents': {
      id: '/portal/documents'
      path: '/documents'
      fullPath: '/portal/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/notifications': {
      id: '/portal/notifications'
      path: '/notifications'
      fullPath: '/portal/notifications'
      preLoaderRoute: typeof PortalNotificationsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/profile': {
      id: '/portal/profile'
      path: '/profile'
      fullPath: '/portal/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/schemes/': {
      id: '/schemes/'
      path: '/schemes'
      fullPath: '/schemes/'
      preLoaderRoute: typeof SchemesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes/$id': {
      id: '/schemes/$id'
      path: '/schemes/$id'
      fullPath: '/schemes/$id'
      preLoaderRoute: typeof SchemesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/schemes/$id': {
      id: '/admin/schemes/$id'
      path: '/$id'
      fullPath: '/admin/schemes/$id'
      preLoaderRoute: typeof AdminSchemesIdRouteImport
      parentRoute: typeof AdminSchemesRoute
    }
    '/approval/applications/$id': {
      id: '/approval/applications/$id'
      path: '/applications/$id'
      fullPath: '/approval/applications/$id'
      preLoaderRoute: typeof ApprovalApplicationsIdRouteImport
      parentRoute: typeof ApprovalRoute
    }
    '/audit/events/$id': {
      id: '/audit/events/$id'
      path: '/events/$id'
      fullPath: '/audit/events/$id'
      preLoaderRoute: typeof AuditEventsIdRouteImport
      parentRoute: typeof AuditRoute
    }
    '/committee/candidates/$id': {
      id: '/committee/candidates/$id'
      path: '/$id'
      fullPath: '/committee/candidates/$id'
      preLoaderRoute: typeof CommitteeCandidatesIdRouteImport
      parentRoute: typeof CommitteeCandidatesRoute
    }
    '/institution/applications/': {
      id: '/institution/applications/'
      path: '/applications'
      fullPath: '/institution/applications/'
      preLoaderRoute: typeof InstitutionApplicationsIndexRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/institution/applications/$id': {
      id: '/institution/applications/$id'
      path: '/applications/$id'
      fullPath: '/institution/applications/$id'
      preLoaderRoute: typeof InstitutionApplicationsIdRouteImport
      parentRoute: typeof InstitutionRoute
    }
    '/officer/applications/$id': {
      id: '/officer/applications/$id'
      path: '/applications/$id'
      fullPath: '/officer/applications/$id'
      preLoaderRoute: typeof OfficerApplicationsIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/grievances/': {
      id: '/officer/grievances/'
      path: '/grievances'
      fullPath: '/officer/grievances/'
      preLoaderRoute: typeof OfficerGrievancesIndexRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/officer/grievances/$id': {
      id: '/officer/grievances/$id'
      path: '/grievances/$id'
      fullPath: '/officer/grievances/$id'
      preLoaderRoute: typeof OfficerGrievancesIdRouteImport
      parentRoute: typeof OfficerRoute
    }
    '/portal/applications/': {
      id: '/portal/applications/'
      path: '/applications'
      fullPath: '/portal/applications/'
      preLoaderRoute: typeof PortalApplicationsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/applications/$id': {
      id: '/portal/applications/$id'
      path: '/applications/$id'
      fullPath: '/portal/applications/$id'
      preLoaderRoute: typeof PortalApplicationsIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/applications/new': {
      id: '/portal/applications/new'
      path: '/applications/new'
      fullPath: '/portal/applications/new'
      preLoaderRoute: typeof PortalApplicationsNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/grievances/': {
      id: '/portal/grievances/'
      path: '/grievances'
      fullPath: '/portal/grievances/'
      preLoaderRoute: typeof PortalGrievancesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/grievances/$id': {
      id: '/portal/grievances/$id'
      path: '/grievances/$id'
      fullPath: '/portal/grievances/$id'
      preLoaderRoute: typeof PortalGrievancesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/grievances/new': {
      id: '/portal/grievances/new'
      path: '/grievances/new'
      fullPath: '/portal/grievances/new'
      preLoaderRoute: typeof PortalGrievancesNewRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/applications/$id/deficiency': {
      id: '/portal/applications/$id/deficiency'
      path: '/deficiency'
      fullPath: '/portal/applications/$id/deficiency'
      preLoaderRoute: typeof PortalApplicationsIdDeficiencyRouteImport
      parentRoute: typeof PortalApplicationsIdRoute
    }
    '/portal/applications/$id/documents': {
      id: '/portal/applications/$id/documents'
      path: '/documents'
      fullPath: '/portal/applications/$id/documents'
      preLoaderRoute: typeof PortalApplicationsIdDocumentsRouteImport
      parentRoute: typeof PortalApplicationsIdRoute
    }
  }
}

interface AdminSchemesRouteChildren {
  AdminSchemesIdRoute: typeof AdminSchemesIdRoute
}

const AdminSchemesRouteChildren: AdminSchemesRouteChildren = {
  AdminSchemesIdRoute: AdminSchemesIdRoute,
}

const AdminSchemesRouteWithChildren = AdminSchemesRoute._addFileChildren(
  AdminSchemesRouteChildren,
)

interface AdminRouteChildren {
  AdminAiRoute: typeof AdminAiRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminNotificationTemplatesRoute: typeof AdminNotificationTemplatesRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPermissionsRoute: typeof AdminPermissionsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSchemesRoute: typeof AdminSchemesRouteWithChildren
  AdminScopesRoute: typeof AdminScopesRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiRoute: AdminAiRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminNotificationTemplatesRoute: AdminNotificationTemplatesRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPermissionsRoute: AdminPermissionsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSchemesRoute: AdminSchemesRouteWithChildren,
  AdminScopesRoute: AdminScopesRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AnalyticsRouteChildren {
  AnalyticsAiRoute: typeof AnalyticsAiRoute
  AnalyticsOperationalRoute: typeof AnalyticsOperationalRoute
  AnalyticsProcessingRoute: typeof AnalyticsProcessingRoute
  AnalyticsSchemeRoute: typeof AnalyticsSchemeRoute
  AnalyticsSelectionRoute: typeof AnalyticsSelectionRoute
  AnalyticsIndexRoute: typeof AnalyticsIndexRoute
}

const AnalyticsRouteChildren: AnalyticsRouteChildren = {
  AnalyticsAiRoute: AnalyticsAiRoute,
  AnalyticsOperationalRoute: AnalyticsOperationalRoute,
  AnalyticsProcessingRoute: AnalyticsProcessingRoute,
  AnalyticsSchemeRoute: AnalyticsSchemeRoute,
  AnalyticsSelectionRoute: AnalyticsSelectionRoute,
  AnalyticsIndexRoute: AnalyticsIndexRoute,
}

const AnalyticsRouteWithChildren = AnalyticsRoute._addFileChildren(
  AnalyticsRouteChildren,
)

interface ApprovalRouteChildren {
  ApprovalQueueRoute: typeof ApprovalQueueRoute
  ApprovalIndexRoute: typeof ApprovalIndexRoute
  ApprovalApplicationsIdRoute: typeof ApprovalApplicationsIdRoute
}

const ApprovalRouteChildren: ApprovalRouteChildren = {
  ApprovalQueueRoute: ApprovalQueueRoute,
  ApprovalIndexRoute: ApprovalIndexRoute,
  ApprovalApplicationsIdRoute: ApprovalApplicationsIdRoute,
}

const ApprovalRouteWithChildren = ApprovalRoute._addFileChildren(
  ApprovalRouteChildren,
)

interface AuditRouteChildren {
  AuditLogRoute: typeof AuditLogRoute
  AuditIndexRoute: typeof AuditIndexRoute
  AuditEventsIdRoute: typeof AuditEventsIdRoute
}

const AuditRouteChildren: AuditRouteChildren = {
  AuditLogRoute: AuditLogRoute,
  AuditIndexRoute: AuditIndexRoute,
  AuditEventsIdRoute: AuditEventsIdRoute,
}

const AuditRouteWithChildren = AuditRoute._addFileChildren(AuditRouteChildren)

interface CommitteeCandidatesRouteChildren {
  CommitteeCandidatesIdRoute: typeof CommitteeCandidatesIdRoute
}

const CommitteeCandidatesRouteChildren: CommitteeCandidatesRouteChildren = {
  CommitteeCandidatesIdRoute: CommitteeCandidatesIdRoute,
}

const CommitteeCandidatesRouteWithChildren =
  CommitteeCandidatesRoute._addFileChildren(CommitteeCandidatesRouteChildren)

interface CommitteeRouteChildren {
  CommitteeCandidatesRoute: typeof CommitteeCandidatesRouteWithChildren
  CommitteeIndexRoute: typeof CommitteeIndexRoute
}

const CommitteeRouteChildren: CommitteeRouteChildren = {
  CommitteeCandidatesRoute: CommitteeCandidatesRouteWithChildren,
  CommitteeIndexRoute: CommitteeIndexRoute,
}

const CommitteeRouteWithChildren = CommitteeRoute._addFileChildren(
  CommitteeRouteChildren,
)

interface FinanceRouteChildren {
  FinanceAwardsRoute: typeof FinanceAwardsRoute
  FinanceDisbursementsRoute: typeof FinanceDisbursementsRoute
  FinanceExceptionsRoute: typeof FinanceExceptionsRoute
  FinanceReconciliationRoute: typeof FinanceReconciliationRoute
  FinanceSanctionsRoute: typeof FinanceSanctionsRoute
  FinanceIndexRoute: typeof FinanceIndexRoute
}

const FinanceRouteChildren: FinanceRouteChildren = {
  FinanceAwardsRoute: FinanceAwardsRoute,
  FinanceDisbursementsRoute: FinanceDisbursementsRoute,
  FinanceExceptionsRoute: FinanceExceptionsRoute,
  FinanceReconciliationRoute: FinanceReconciliationRoute,
  FinanceSanctionsRoute: FinanceSanctionsRoute,
  FinanceIndexRoute: FinanceIndexRoute,
}

const FinanceRouteWithChildren =
  FinanceRoute._addFileChildren(FinanceRouteChildren)

interface InstitutionRouteChildren {
  InstitutionClarificationsRoute: typeof InstitutionClarificationsRoute
  InstitutionUsersRoute: typeof InstitutionUsersRoute
  InstitutionVerificationsRoute: typeof InstitutionVerificationsRoute
  InstitutionIndexRoute: typeof InstitutionIndexRoute
  InstitutionApplicationsIdRoute: typeof InstitutionApplicationsIdRoute
  InstitutionApplicationsIndexRoute: typeof InstitutionApplicationsIndexRoute
}

const InstitutionRouteChildren: InstitutionRouteChildren = {
  InstitutionClarificationsRoute: InstitutionClarificationsRoute,
  InstitutionUsersRoute: InstitutionUsersRoute,
  InstitutionVerificationsRoute: InstitutionVerificationsRoute,
  InstitutionIndexRoute: InstitutionIndexRoute,
  InstitutionApplicationsIdRoute: InstitutionApplicationsIdRoute,
  InstitutionApplicationsIndexRoute: InstitutionApplicationsIndexRoute,
}

const InstitutionRouteWithChildren = InstitutionRoute._addFileChildren(
  InstitutionRouteChildren,
)

interface OfficerRouteChildren {
  OfficerClarificationsRoute: typeof OfficerClarificationsRoute
  OfficerDeficienciesRoute: typeof OfficerDeficienciesRoute
  OfficerNotificationsRoute: typeof OfficerNotificationsRoute
  OfficerQueueRoute: typeof OfficerQueueRoute
  OfficerIndexRoute: typeof OfficerIndexRoute
  OfficerApplicationsIdRoute: typeof OfficerApplicationsIdRoute
  OfficerGrievancesIdRoute: typeof OfficerGrievancesIdRoute
  OfficerGrievancesIndexRoute: typeof OfficerGrievancesIndexRoute
}

const OfficerRouteChildren: OfficerRouteChildren = {
  OfficerClarificationsRoute: OfficerClarificationsRoute,
  OfficerDeficienciesRoute: OfficerDeficienciesRoute,
  OfficerNotificationsRoute: OfficerNotificationsRoute,
  OfficerQueueRoute: OfficerQueueRoute,
  OfficerIndexRoute: OfficerIndexRoute,
  OfficerApplicationsIdRoute: OfficerApplicationsIdRoute,
  OfficerGrievancesIdRoute: OfficerGrievancesIdRoute,
  OfficerGrievancesIndexRoute: OfficerGrievancesIndexRoute,
}

const OfficerRouteWithChildren =
  OfficerRoute._addFileChildren(OfficerRouteChildren)

interface PortalApplicationsIdRouteChildren {
  PortalApplicationsIdDeficiencyRoute: typeof PortalApplicationsIdDeficiencyRoute
  PortalApplicationsIdDocumentsRoute: typeof PortalApplicationsIdDocumentsRoute
}

const PortalApplicationsIdRouteChildren: PortalApplicationsIdRouteChildren = {
  PortalApplicationsIdDeficiencyRoute: PortalApplicationsIdDeficiencyRoute,
  PortalApplicationsIdDocumentsRoute: PortalApplicationsIdDocumentsRoute,
}

const PortalApplicationsIdRouteWithChildren =
  PortalApplicationsIdRoute._addFileChildren(PortalApplicationsIdRouteChildren)

interface PortalRouteChildren {
  PortalAwardsRoute: typeof PortalAwardsRoute
  PortalDeficienciesRoute: typeof PortalDeficienciesRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalNotificationsRoute: typeof PortalNotificationsRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalApplicationsIdRoute: typeof PortalApplicationsIdRouteWithChildren
  PortalApplicationsNewRoute: typeof PortalApplicationsNewRoute
  PortalGrievancesIdRoute: typeof PortalGrievancesIdRoute
  PortalGrievancesNewRoute: typeof PortalGrievancesNewRoute
  PortalApplicationsIndexRoute: typeof PortalApplicationsIndexRoute
  PortalGrievancesIndexRoute: typeof PortalGrievancesIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAwardsRoute: PortalAwardsRoute,
  PortalDeficienciesRoute: PortalDeficienciesRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalNotificationsRoute: PortalNotificationsRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalApplicationsIdRoute: PortalApplicationsIdRouteWithChildren,
  PortalApplicationsNewRoute: PortalApplicationsNewRoute,
  PortalGrievancesIdRoute: PortalGrievancesIdRoute,
  PortalGrievancesNewRoute: PortalGrievancesNewRoute,
  PortalApplicationsIndexRoute: PortalApplicationsIndexRoute,
  PortalGrievancesIndexRoute: PortalGrievancesIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRouteWithChildren,
  ApprovalRoute: ApprovalRouteWithChildren,
  AuditRoute: AuditRouteWithChildren,
  CommitteeRoute: CommitteeRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqsRoute: FaqsRoute,
  FinanceRoute: FinanceRouteWithChildren,
  ForbiddenRoute: ForbiddenRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GrievanceRoute: GrievanceRoute,
  GuidelinesRoute: GuidelinesRoute,
  InstitutionRoute: InstitutionRouteWithChildren,
  LoginRoute: LoginRoute,
  MfaRoute: MfaRoute,
  NoticesRoute: NoticesRoute,
  OfficerRoute: OfficerRouteWithChildren,
  OtpVerifyRoute: OtpVerifyRoute,
  PortalRoute: PortalRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SchemesIdRoute: SchemesIdRoute,
  SchemesIndexRoute: SchemesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
